
import java.awt.Dimension;
import java.awt.image.BufferedImage;

public class InternalFrame extends javax.swing.JInternalFrame {

    public InternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Imagen_Dinamico1 = new Panel_Imagen_Dinamico();
        panelImagen1 = new PanelImagen();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        panel_Imagen_Dinamico1.setAutoscrolls(true);
        panel_Imagen_Dinamico1.setPreferredSize(new java.awt.Dimension(0, 0));

        panelImagen1.setAutoscrolls(true);
        panelImagen1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        panel_Imagen_Dinamico1.setViewportView(panelImagen1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Imagen_Dinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Imagen_Dinamico1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelImagen panelImagen1;
    private Panel_Imagen_Dinamico panel_Imagen_Dinamico1;
    // End of variables declaration//GEN-END:variables

    public PanelImagen getPanelImagen1() {
        return panelImagen1;
    }
    public void setImagen(BufferedImage i){
        panelImagen1.setI(i);
        panelImagen1.setPreferredSize(new Dimension((int)i.getWidth(),(int)i.getHeight()));
        panelImagen1.paintComponent(panelImagen1.getGraphics());
    }
}
